# Utilisez l'image officielle de PostgreSQL
FROM postgres:latest

# Copiez les scripts SQL dans le répertoire d'initialisation
COPY init.sql /docker-entrypoint-initdb.d/

# Vous pouvez également ajouter d'autres configurations si nécessaire
